
name: GitHub Actions Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest      
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Build and run the program.
        working-directory: io_functions
        run: |
            gcc ./io_func.c
            ./a.out
    