
name: GitHub Actions Test
on: [push]

# 'jobs' here is a "dictionary" ( like {"key":"value"} in JSON ) and it can have different fields, 
# but for now we just need some  # of them.
jobs:
  test_temperature_converter:
    # 'runs-on' specifies on which OS we run our job and we select ubuntu.
    runs-on: ubuntu-latest 
    steps:
      # The fisrt step is almost always this special step `actions/checkout@v3` which just does 'git clone' 
      # and 'git checkout'. Without that step, we simply won't get our source code files here.
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Build and run the program test_convert_to_celsius.
        working-directory: celsius_farenheit
        run: |
            gcc ./convert_to_celsius.c
            ./a.out

      - name: Build and run the program celsius_farenheit.
        working-directory: celsius_farenheit
        run: |
            gcc -o b.out ./temperature_converter.c 
            ./b.out
    
